import esbuild from "esbuild";
import process from "process";
import path from "path";
import { createRequire } from "module";
import builtins from "builtin-modules";

const require = createRequire(import.meta.url);

const inlineCssPlugin = {
        name: "inline-css",
        setup(build) {
                build.onResolve({ filter: /\.css$/ }, (args) => {
                        const isRelative = args.path.startsWith("./") || args.path.startsWith("../") || args.path.startsWith("/");
                        const resolvedPath = isRelative
                                ? path.resolve(args.resolveDir, args.path)
                                : require.resolve(args.path, { paths: [args.resolveDir] });

                        return {
                                path: resolvedPath,
                                namespace: "inline-css",
                        };
                });

                build.onLoad({ filter: /.*/, namespace: "inline-css" }, async (args) => {
                        const result = await esbuild.build({
                                entryPoints: [args.path],
                                bundle: true,
                                write: false,
                                loader: {
                                        ".css": "css",
                                        ".ttf": "dataurl",
                                        ".woff": "dataurl",
                                        ".woff2": "dataurl",
                                },
                        });

                        return {
                                contents: `export default ${JSON.stringify(result.outputFiles[0].text)};`,
                                loader: "js",
                        };
                });
        },
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
        banner: {
                js: banner,
        },
        entryPoints: ["main.ts"],
        bundle: true,
        plugins: [inlineCssPlugin],
        external: [
                "obsidian",
                "electron",
                "@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
                "@lezer/highlight",
                "@lezer/lr",
                ...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
        treeShaking: true,
        outfile: "bin/main.js",
        loader: {
                '.ttf': 'dataurl',
                '.woff': 'dataurl',
                '.woff2': 'dataurl',
        },
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
